console.log("Hello world, the usual fair")
const containerDiv = document.querySelector("#container")
const divTopRow = document.createElement("div")
const div1 = document.createElement("div")
const div2 = document.createElement("div")
const div3 = document.createElement("div")
const div4 = document.createElement("div")
const div5 = document.createElement("div")
const div6 = document.createElement("div")
div6.textContent = "test"
const div7 = document.createElement("div")
const div8 = document.createElement("div")
const div9 = document.createElement("div")
const div10 = document.createElement("div")
const div11 = document.createElement("div")
const div12 = document.createElement("div")
const div13 = document.createElement("div")
div13.textContent = "test"
const div14 = document.createElement("div")
const div15 = document.createElement("div")
const div16 = document.createElement("div")
containerDiv.appendChild(divTopRow)
divTopRow.appendChild(div1)
divTopRow.appendChild(div2)
divTopRow.appendChild(div3)
divTopRow.appendChild(div4)
divTopRow.appendChild(div5)
divTopRow.appendChild(div6)
divTopRow.appendChild(div7)
divTopRow.appendChild(div8)
divTopRow.appendChild(div9)
divTopRow.appendChild(div10)
divTopRow.appendChild(div11)
divTopRow.appendChild(div12)
divTopRow.appendChild(div13)
divTopRow.appendChild(div14)
divTopRow.appendChild(div15)
divTopRow.appendChild(div16)
